name: GitHub-Profile-3D-Contrib

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: generate-github-profile-3d-contrib
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Generate Github 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: pre-commit-autoupdate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feat/3d_contrib
          title: Generate Github 3D Contrib
          commit-message: "Feat: Generate Github 3D Contrib"
          body: Generate Github 3D Contrib.
  
      - name: Auto Merge Pull Request
        if: steps.pre-commit-autoupdate.outputs.pull-request-number
        run: |
          gh pr merge --auto --merge feat/3d_contrib
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
