name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    name: generate-github-profile-3d-contrib
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Generate Github 3D Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.9.0
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Folder
        run: |
          cp -R profile-3d-contrib .github
          rm -rf profile-3d-contrib

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master  # push to this branch
          branch: feat/3d_contrib
          title: "feat: Generate Github 3D Contrib"
          body: "Generate Github 3D Contrib."
          commit-message: "feat: Generate Github 3D Contrib"
          delete-branch: true

      - name: Auto Merge Pull Request
        continue-on-error: true
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge --merge feat/3d_contrib
